// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_lK6-BiIsPB2gUGs_AKkVUkVg1KDjWE',
    appId: '1:471748242246:web:2f06dbe66de82179b4d347',
    messagingSenderId: '471748242246',
    projectId: 'aubsystemm',
    authDomain: 'aubsystemm.firebaseapp.com',
    storageBucket: 'aubsystemm.appspot.com',
    measurementId: 'G-EKWKVSJTDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB9KYchkQISv6P-q_n7NlDaylh6-xmvwA',
    appId: '1:471748242246:android:f88313aeaa1a06d4b4d347',
    messagingSenderId: '471748242246',
    projectId: 'aubsystemm',
    storageBucket: 'aubsystemm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2rlCSIW4YQfpVcTYaqRdqwHl2Q_wzrJE',
    appId: '1:471748242246:ios:156c7cee480b3049b4d347',
    messagingSenderId: '471748242246',
    projectId: 'aubsystemm',
    storageBucket: 'aubsystemm.appspot.com',
    iosBundleId: 'com.aub.aubGymsystem',
  );
}
